### ISSUE TITLE
re-initialize after exit to vive menu

### ISSUE THREAD

**Issue by ckromero** [ckromero/cvrtain#8]
If you exit to the Steam VR menu while the app is running and then return the controllers don't seem to come back int he game. This means you're looking at two hands stuck in front of you, bummer! Have a look?

**Comment by OwenTheBell** [comment]
So what's going on when I tested this is that when you enter the steam menu and then exit it disables the controller objects and then doesn't re-enable them. There are two ways to handle this:
- Either I turn on some debug settings that can capture when the menu is activated/de-activated and then manually re-enable the controllers (I'm not 100% sure this will work easily, but it's possible)
- Or we can set launch arguments in steam that prevent the menu from ever launching. I think this is probably the better solution since then we prevent players accidentally triggering the menu during the show.

**Comment by ckromero** [comment]
Ah def the latter if you can make that's work, thanks

**Comment by OwenTheBell** [comment]
Ok, we can do this easily by just going into the SteamVR Settings/Developer and unchecking "Enable VR Dashboard".

We have a note of how to do this here so I'm going to go ahead and mark this issue closed.
